### PR TITLE
Implementing decadac fine voltage as a customised instrument

### PR DESCRIPTION
**Pull request by Dominik-Vogel**
requires PR876 from qcodes

### CODE REVIEW

**Comment by ThorvaldLarsen** [comment]
Do you want this one to go into the master branch? We are working out of the all-wrappers branch at the moment.
Guess it would be nice to move that at some point.

**Comment by Dominik-Vogel** [comment]
Thank you for pointing that out. I accidentally chose master not all_wrappers. We can migrate to master at some later point.

**Comment by Dominik-Vogel** [comment]
https://github.com/isaacs/github/issues/18

this is really worth scrolling through :-)

**Comment by ThorvaldLarsen** [comment]
Nice! Was almost expecting the thread to end with: still not possible.

**Pull request merged**
