### PR TITLE
Add transpose option for show_num

### PR DESCRIPTION
**Pull request by ThorvaldLarsen**
See title.

### CODE REVIEW

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel when you have time can you take a quick look to see if okay to merge?
The new feature has been tested.

**Comment by ThorvaldLarsen** [comment]
Actually only works when creating one plot. Something goes wrong if more plots are to be created...

**Comment by Dominik-Vogel** [comment]
sure, let me know when you figure out the bug or need assistance in finding it.

**Comment by ThorvaldLarsen** [comment]
Turns out the issue is if several dataset have the same setpoints. That is set_arrays points to the same thing in memory when I then swap the two set_arrays they are swapped for all. This becomes a problem when the loop then swap the same set_points on second run through.
```
data.alazar_ctrl_rec_f2_phase_data.set_arrays[1] is data.alazar_ctrl_rec_f2_mag_data.set_arrays[1]
Out[8]: True
```
For now I have enforced that a dataset name is provided so that only one graph is produced. It still does what we want although a bit anoying to have to run it many times if there are multiple dataset.
However, I dont think it is worth spending too much time on show_num as it will be outdated when we soonish move to the new dataset.

I think it should be fine to merge as it is now.

**Pull request merged**
