### PR TITLE
rename logging to logger to resolve naming conflict with python logging

### PR DESCRIPTION
**Pull request by Dominik-Vogel**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
You need to change file_setup and the moved init file too I think

**Comment by Dominik-Vogel** [comment]
thanks for pointing that out

**Comment by jenshnielsen** [comment]
qdev-wrappers/qdev_wrappers/logger/__init__.py still needs to be updated

**Comment by jenshnielsen** [comment]
I also need an explicit import of logging.handlers in logging_functions.py to make this run

**Pull request merged**
