### PR TITLE
Live plotting and sweep functions

### PR DESCRIPTION
**Pull request by emartinez**
- The sweep functions (do0d, do1d, do2d) work roughly as they used to, plus a progress bar with timing.

- For the live plotting there is a daemon that has to be run once in a stand-alone Python terminal. The daemon will listen to updates to the database, plot them as they come, and save them.

### CODE REVIEW

**Comment by nataliejpg** [comment]
@Dominik-Vogel are we waiting on any reason not to go ahead and merge this? maybe the name of 'sweep_functions_new' is a bit dodgy but we can always fix it later when everyone is on the new dataset right? @emartinez I assume from your end this is good to go?

**Comment by nataliejpg** [comment]
I guess the main thing missing is that the doNd here do not take tasks, not sure if that's a bad thing or if people should just learn to write their own loops if they want a task executed.

**Comment by Dominik-Vogel** [comment]
I think we should not support tasks with the new doNds. The whole point was to get rid of this construct.
If @emartinez feels it is ready for it, I can merge it.

**Comment by nataliejpg** [comment]
Thanks @GateBuilder. Could you point me toward the current reccomended live plotting software?

**Pull request closed without merging**
