### PR TITLE
Data num getter

### PR DESCRIPTION
**Pull request by nataliejpg**
replaces #26 using method suggested by @ThorvaldLarsen to get 'data_num' based on location of dataset.

### CODE REVIEW

**Comment by nataliejpg** [comment]
@jenshnielsen does this look better/acceptable to you?

**Comment by jenshnielsen** [comment]
@nataliejpg I think this looks good

**Comment by nataliejpg** [comment]
@jenshnielsen good enough to merge? ;)

**Comment by jenshnielsen** [comment]
I have not tested it but feel free to merge if you have

**Pull request merged**
