### PR TITLE
only specify named channels in config for qdac

### LINKED ISSUE #36: Qdac_ext not working
- want to change it so that it loops over entries in the config file instead of number of channels.
- voltage parameter is not channel.volt as for decadac.

### PR DESCRIPTION
**Pull request by Dominik-Vogel**
fixes #36

### CODE REVIEW

**Comment by ThorvaldLarsen** [comment]
We also need to fix how it calls the parameter. The qdac driver does not have channels.

**Comment by ThorvaldLarsen** [comment]
just noticed that there might be a different version of the qdac driver with channels... maybe we just need to use that one instead. I dont know how that one works though.

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel I tested this at QT1 with Lucas. Only thing more that needs to be changed is line 29:
param = channel.volt -> param = channel.v

**Comment by Dominik-Vogel** [comment]
@ThorvaldLarsen thank your for testing and pointing that out. This is fixed now and we can merge.

**Pull request merged**
