### PR TITLE
Znb

### PR DESCRIPTION
**Pull request by ThorvaldLarsen**
Move `self.channels.autoscale()` inside `if` statements so that it is only called if channels are created. Previously autoscale would throw an error if ZNB is initialized with no channels.

@Dominik-Vogel can you take a quick look? Should be fast to merge.

### CODE REVIEW

**Comment by Dominik-Vogel** [comment]
I would prefer a simpler approach:
leave it where it is and check if it has channels. This makes it safer if we are going to implement other types of channels.

**Comment by ThorvaldLarsen** [comment]
Not sure what you mean by this.

**Comment by ThorvaldLarsen** [comment]
@Dominik-Vogel actually thinking more about it I think we should just completely remove it. The VNA is initialized with RF power off and running autoscale with power off doesn't really make sense.

**Comment by Dominik-Vogel** [comment]
ok that kinda makes sense,

**Pull request merged**
