### PR TITLE
Add offset as parameter_attribute in SCFG

### PR DESCRIPTION
**Pull request by ThorvaldLarsen**
@Dominik-Vogel by chance I discovered my issue with `monitor.update_all()`. My problem was I didn't call it from the initialized monitor object. With this change one can do `scfg.monitor.update_all()`.

Also added `offset` to the list of parameter attributes.

### CODE REVIEW

**Comment by Dominik-Vogel** [comment]
So you are saying that with this PR
```
scfg.monitor.update_all()
```
works for you, but:
```
Monitor.running.update_all()
```
does not?

👍 fro adding offset! I totally forgot to put it into the station configurator as well when I added it to the parameter. It is great to see that someone is using the offset!

**Comment by ThorvaldLarsen** [comment]
I did not know about the `Monitor.running` part. Thanks! 

Is there a doc for the monitor somewhere - I could not find one. Maybe a short writeup would be good at some point?

**Comment by ThorvaldLarsen** [comment]
I removed the changes to the monitor part. But guess we can still merge the offset.

**Comment by Dominik-Vogel** [comment]
True, we are lacking documentation. Not only for the monitor.

**Pull request merged**
