### PR TITLE
Add support for ArrayParameter in DoNds

### PR DESCRIPTION
**Pull request by Dominik-Vogel**
This is inspired by #166

see diff here:
https://github.com/qdev-dk/qdev-wrappers/compare/80516e7660355501cbd8f9545316f1a374298af0...ThorvaldLarsen:doNd_save_image

### CODE REVIEW

**Comment by Dominik-Vogel** [comment]
@ThorvaldLarsen what is this sleep about?
https://github.com/ThorvaldLarsen/qdev-wrappers/blob/9df2e3359804a9dc4e9172a7de4194abb25e8080/qdev_wrappers/dataset/doNd.py#L112

**Comment by Dominik-Vogel** [comment]
I have looked at the test and realized, that it is not actually necessary. Maybe it was when the changes first were made.
@ThorvaldLarsen 
https://github.com/QCoDeS/Qcodes/blob/bc0118c1ee4b5a4f54b2a56bf2dbe1adcde4b59f/qcodes/dataset/measurements.py#L869-L896

**Comment by jenshnielsen** [comment]
The multiparameter part is afaik still not handled within qcodes

**Comment by Dominik-Vogel** [comment]
True, but this we should handle in qcodes.

**Comment by ThorvaldLarsen** [comment]
Not sure about the sleep. Also this PR is quite old so seems very plausible that what it solved has since been fixed in qcodes.

**Comment by ThorvaldLarsen** [comment]
Well not this PR, but the original one I made to handle array paramters with new dataset

**Pull request closed without merging**
