### PR TITLE
updates setting setpoints on alazar channel data parameter

### PR DESCRIPTION
**Pull request by nataliejpg**
setting setpoints can now be done via set_setpoints_and_labels function which is also called by prepare_channel. The setpoints, names, labels and units. See example notebook for details. Default behaviour remains the same

- [x] test

### CODE REVIEW

**Comment by ThorvaldLarsen** [comment]
Anders has been running with this PR for a week without any issues. So this has been tested with the cQED code at T3,T11,QT2.

**Comment by nataliejpg** [comment]
great, thanks @ThorvaldLarsen. We've been using it at T2 as well on both measurement pcs but I didn't test the two dimensional parameters yet and was thinking I should run the example notebook to check that works too. I will try to do that today or early next week though and then we can merge

**Comment by nataliejpg** [comment]
ok this is now ready I think. I've been using it for 1d traces with demodulation for a few months and have tested the example notebook for 1d and 2d traces (but without only noise input) @ThorvaldLarsen or @jenshnielsen could you review?

**Comment by nataliejpg** [comment]
also I couldn't resist do I deleted the "Qcodes example with Alazar ATS9360 old controller" notebook and the "acquisition_parametersold.py" because unless I'm wrong(?) its pretty much impossible that anyone is using them @jenshnielsen

**Pull request closed without merging**
